### ISSUE TITLE
Grave inventory gui

### ISSUE THREAD

**Issue by NightKosh** [NightKosh/GraveStone-mod#149]
Add grave gui screen(open at right click with shovel)
Also try to allow to use any type of shovel(even from another mods)

**Comment by NightKosh** [comment]
Add configuration option to allow to open graves without shovel in hand.

**Comment by axelpx** [comment]
That would be so cool to have an interface for the graves for 1.7.10. It would make graves compatible with WorldGuard, Factions and other protection plugins.

**Comment by NightKosh** [comment]
net.minecraft.util.ReportedException: Updating screen events
	at net.minecraft.client.Minecraft.runTick(Unknown Source) ~[Minecraft.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Unknown Source) ~[Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Unknown Source) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Unknown Source) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
	at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source) [start/:?]
	at GradleStart.main(Unknown Source) [start/:?]
Caused by: java.lang.StackOverflowError
	at net.minecraft.nbt.NBTTagCompound.copy(Unknown Source) ~[NBTTagCompound.class:?]
	at net.minecraft.item.ItemStack.copy(Unknown Source) ~[ItemStack.class:?]
	at net.minecraft.inventory.Container.slotClick(Unknown Source) ~[Container.class:?]
	at net.minecraft.inventory.Container.retrySlotClick(Unknown Source) ~[Container.class:?]
	at net.minecraft.inventory.Container.slotClick(Unknown Source) ~[Container.class:?]
	at net.minecraft.inventory.Container.retrySlotClick(Unknown Source) ~[Container.class:?]
	at net.minecraft.inventory.Container.slotClick(Unknown Source) ~[Container.class:?]
	at net.minecraft.inventory.Container.retrySlotClick(Unknown Source) ~[Container.class:?]
	at net.minecraft.inventory.Container.slotClick(Unknown Source) ~[Container.class:?]
	at net.minecraft.inventory.Container.retrySlotClick(Unknown Source) ~[Container.class:?]
	at net.minecraft.inventory.Container.slotClick(Unknown Source) ~[Container.class:?]
	at net.minecraft.inventory.Container.retrySlotClick(Unknown Source) ~[Container.class:?]
