### ISSUE TITLE
Sever Freeze at catacombs generation

### ISSUE THREAD

**Issue by NightKosh** [NightKosh/GraveStone-mod#171]
GrinningMoon:

I wanted to bring a possible bug to your attention. I've been experiencing some freezes on my Cauldron (build 1291) server due to CPU core/thread locking. I was trying to pregenerate my world by using WorldBorder (bukkit plugin) to load chunks. After a certain amount of time (~10 mins) the server would freeze.

Using VisualVM, I was able to pull the following info from a thread dump of the CPU:

at gravestone.structures.catacombs.components.Fence.createEntrance(Fence.java:171)
at gravestone.structures.catacombs.components.Fence.addComponentParts(Fence.java:37)
at gravestone.structures.catacombs.CatacombsSurface.build(CatacombsSurface.java:119)
at gravestone.structures.catacombs.CatacombsSurface. (CatacombsSurface.java:29)
at gravestone.structures.catacombs.CatacombsGenerator.generate(CatacombsGenerator.java:48)
at gravestone.structures.GraveStoneWorldGenerator.generateSurface(GraveStoneWorldGenerator.java:35)
at gravestone.structures.GraveStoneWorldGenerator.generate(GraveStoneWorldGenerator.java:28)
at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:130)
at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:394)
at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1160)
at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:249)
at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:169)
at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:137)
at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:260)
at net.minecraft.world.World.func_72964_e(World.java:739)
at net.minecraft.world.World.func_147439_a(World.java:665)
at net.minecraft.world.World.func_147460_e(World.java:1068)
at net.minecraft.world.World.func_147459_d(World.java:1027)
at net.minecraft.world.World.func_147444_c(World.java:988)
at net.minecraft.world.World.markAndNotifyBlock(World.java:844)
at net.minecraft.world.World.func_147465_d(World.java:822)
at plantmegapack.worldgen.PMPGenBase.spawnPlant(PMPGenBase.java:181)
at plantmegapack.worldgen.PMPGenBase.spawnPlantCluster(PMPGenBase.java:137)
at plantmegapack.worldgen.PMPWorldGenerator.generateSurface(PMPWorldGenerator.java:99)
at plantmegapack.worldgen.PMPWorldGenerator.generate(PMPWorldGenerator.java:46)
at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:130)
at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:394)
at org.bukkit.craftbukkit.v1_7_R4.CraftWorld.chunkLoadPostProcess(CraftWorld.java:288)
at org.bukkit.craftbukkit.v1_7_R4.CraftWorld.loadChunk(CraftWorld.java:266)
at com.wimbli.WorldBorder.WorldFillTask.run(WorldFillTask.java:205)
at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:862)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
at java.lang.Thread.run(Unknown Source)

As you can see at the top, it looks like the CPU stalled when it was trying to create the entrance to the catacomb graveyard ("Fence.createEntrance"). Disabling catacomb graveyard generation fixes the issue so I'm guessing that it was the problem. Maybe there is something messing it up if a player isn't generating the structure?

I like the graveyard generation but it's not that big of an issue for me. I figured you may want this info in case you want to look into it or maybe post it as a known issue or whatever.

Never did say but I really do like your mod, the skull crawlers creep me the f out and it's pretty funny to imagine a skeleton's skull popping off and chasing you!

If you need help tracking the issue, let me know if there is any other info I can provide.

Thanks,

GM

**Comment by DPxKnightxZero** [comment]
Cauldron is dead.
