### ISSUE TITLE
Crash On Death

### ISSUE THREAD

**Issue by DPxKnightxZero** [NightKosh/GraveStone-mod#172]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 4/8/15 3:53 PM
Description: Ticking memory connection

java.lang.ArrayIndexOutOfBoundsException: -128
	at gravestone.core.compatibility.GSCompatibilityTwilightForest.checkForCharmOfKeeping(GSCompatibilityTwilightForest.java:123)
	at gravestone.core.compatibility.GSCompatibilityTwilightForest.handleCharmsOfKeeping(GSCompatibilityTwilightForest.java:30)
	at gravestone.block.GraveStoneHelper.createPlayerGrave(GraveStoneHelper.java:516)
	at gravestone.core.event.GSEventsHandler.onEntityLivingDeath(GSEventsHandler.java:48)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_598_GSEventsHandler_onEntityLivingDeath_LivingDeathEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:303)
	at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:405)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:855)
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1034)
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:491)
	at micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP.func_70097_a(GCEntityPlayerMP.java:73)
	at net.minecraft.entity.EntityLivingBase.func_70069_a(EntityLivingBase.java:1014)
	at net.minecraft.entity.player.EntityPlayer.func_70069_a(EntityPlayer.java:1776)
	at net.minecraft.entity.Entity.func_70064_a(Entity.java:916)
	at net.minecraft.entity.EntityLivingBase.func_70064_a(EntityLivingBase.java:182)
	at net.minecraft.entity.player.EntityPlayerMP.func_71122_b(EntityPlayerMP.java:596)
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:405)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
	at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at gravestone.core.compatibility.GSCompatibilityTwilightForest.checkForCharmOfKeeping(GSCompatibilityTwilightForest.java:123)
	at gravestone.core.compatibility.GSCompatibilityTwilightForest.handleCharmsOfKeeping(GSCompatibilityTwilightForest.java:30)
	at gravestone.block.GraveStoneHelper.createPlayerGrave(GraveStoneHelper.java:516)
	at gravestone.core.event.GSEventsHandler.onEntityLivingDeath(GSEventsHandler.java:48)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_598_GSEventsHandler_onEntityLivingDeath_LivingDeathEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:303)
	at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:405)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:855)
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1034)
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:491)
	at micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP.func_70097_a(GCEntityPlayerMP.java:73)
	at net.minecraft.entity.EntityLivingBase.func_70069_a(EntityLivingBase.java:1014)
	at net.minecraft.entity.player.EntityPlayer.func_70069_a(EntityPlayer.java:1776)
	at net.minecraft.entity.Entity.func_70064_a(Entity.java:916)
	at net.minecraft.entity.EntityLivingBase.func_70064_a(EntityLivingBase.java:182)
	at net.minecraft.entity.player.EntityPlayerMP.func_71122_b(EntityPlayerMP.java:596)
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:405)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
	at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@68b99a43
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_40, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1262981768 bytes (1204 MB) / 2134114304 bytes (2035 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94

**Comment by NightKosh** [comment]
o_O.
How you get more than 127 items slots in inventory?

**Comment by DPxKnightxZero** [comment]
Okay I think yous should make a compatibility fix for infinite inventory located here. https://drone.io/github.com/Funwayguy/InfiniteInvo/files

**Comment by NightKosh** [comment]
Hm.. Twilight forest compatibility module wasn't developed to support more than 40 items(default minecraft inventory size) After this fix it will support over 2G of Slots. Just tested and all works fine except one thing - it looks like "Twilight forest" charm of keeping have the same problem(it doesn't works with more than 36 slots of inventory).

**Comment by NightKosh** [comment]
So inform Benimatic about it.

**Comment by NightKosh** [comment]
Also it doesn't compatible with "Battle gear" mod

**Comment by DPxKnightxZero** [comment]
I only want infinfinite inventory fix because I have my inventory max to be exactly 10 times the max slots IE 270 slots.

**Comment by NightKosh** [comment]
There aren't any limits for graves inventory. Try latest version(2.12.1) it must works perfectly.

**Comment by DPxKnightxZero** [comment]
Will do!

**Comment by DPxKnightxZero** [comment]
So do I save it like this?
# This value must be between 0 an 40(in this case all items will be stored)!
    I:SavedItemsCount=270
    B:ShowGravesRemovingMessages=true
    B:ShowNightStoneMessage=true
    I:SpawnChance=100
    B:SpawnMobAtGraveDestruction=true

**Comment by NightKosh** [comment]
This option was added much earlier than any support with another mods was added...and it still not changed(except how it works)... Its value matter only if you want less than 40(vanilla inventory size) items otherwise it will store all items.

**Comment by DPxKnightxZero** [comment]
Okay so just make the config say 40?

**Comment by NightKosh** [comment]
Yep.)

**Comment by DPxKnightxZero** [comment]
It was working until someone managed to unlock 50 slots then the game crashed server side. ---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 09/04/15 00:30
Description: Ticking entity

java.lang.IndexOutOfBoundsException: Index: -128, Size: 283
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
	at java.util.LinkedList.get(LinkedList.java:476)
	at gravestone.tileentity.GSGraveStoneItems.setItems(GSGraveStoneItems.java:100)
	at gravestone.tileentity.TileEntityGSGrave.setItems(TileEntityGSGrave.java:64)
	at gravestone.block.BlockGSGraveStone.createOnDeath(BlockGSGraveStone.java:771)
	at gravestone.block.GraveStoneHelper.createGrave(GraveStoneHelper.java:542)
	at gravestone.block.GraveStoneHelper.createPlayerGrave(GraveStoneHelper.java:534)
	at gravestone.core.event.GSEventsHandler.onEntityLivingDeath(GSEventsHandler.java:48)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_517_GSEventsHandler_onEntityLivingDeath_LivingDeathEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:303)
	at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:405)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:855)
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1034)
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:491)
	at micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP.func_70097_a(GCEntityPlayerMP.java:73)
	at lycanite.lycanitesmobs.api.entity.EntityCreatureBase.attackEntityAsMob(EntityCreatureBase.java:1711)
	at lycanite.lycanitesmobs.api.entity.EntityCreatureBase.meleeAttack(EntityCreatureBase.java:1660)
	at lycanite.lycanitesmobs.freshwatermobs.entity.EntityZephyr.meleeAttack(EntityZephyr.java:102)
	at lycanite.lycanitesmobs.api.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:198)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:103)
	at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:540)
	at lycanite.lycanitesmobs.api.entity.EntityCreatureBase.func_70619_bc(EntityCreatureBase.java:1066)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1774)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
	at lycanite.lycanitesmobs.api.entity.EntityCreatureBase.func_70636_d(EntityCreatureBase.java:1073)
	at lycanite.lycanitesmobs.api.entity.EntityCreatureAgeable.func_70636_d(EntityCreatureAgeable.java:95)
	at lycanite.lycanitesmobs.api.entity.EntityCreatureTameable.func_70636_d(EntityCreatureTameable.java:170)
	at lycanite.lycanitesmobs.freshwatermobs.entity.EntityZephyr.func_70636_d(EntityZephyr.java:122)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
	at lycanite.lycanitesmobs.api.entity.EntityCreatureBase.func_70071_h_(EntityCreatureBase.java:1029)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
	at java.util.LinkedList.get(LinkedList.java:476)
	at gravestone.tileentity.GSGraveStoneItems.setItems(GSGraveStoneItems.java:100)
	at gravestone.tileentity.TileEntityGSGrave.setItems(TileEntityGSGrave.java:64)
	at gravestone.block.BlockGSGraveStone.createOnDeath(BlockGSGraveStone.java:771)
	at gravestone.block.GraveStoneHelper.createGrave(GraveStoneHelper.java:542)
	at gravestone.block.GraveStoneHelper.createPlayerGrave(GraveStoneHelper.java:534)
	at gravestone.core.event.GSEventsHandler.onEntityLivingDeath(GSEventsHandler.java:48)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_517_GSEventsHandler_onEntityLivingDeath_LivingDeathEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:303)
	at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:405)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:855)
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1034)
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:491)
	at micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP.func_70097_a(GCEntityPlayerMP.java:73)
	at lycanite.lycanitesmobs.api.entity.EntityCreatureBase.attackEntityAsMob(EntityCreatureBase.java:1711)
	at lycanite.lycanitesmobs.api.entity.EntityCreatureBase.meleeAttack(EntityCreatureBase.java:1660)
	at lycanite.lycanitesmobs.freshwatermobs.entity.EntityZephyr.meleeAttack(EntityZephyr.java:102)
	at lycanite.lycanitesmobs.api.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:198)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:103)
	at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:540)
	at lycanite.lycanitesmobs.api.entity.EntityCreatureBase.func_70619_bc(EntityCreatureBase.java:1066)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1774)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
	at lycanite.lycanitesmobs.api.entity.EntityCreatureBase.func_70636_d(EntityCreatureBase.java:1073)
	at lycanite.lycanitesmobs.api.entity.EntityCreatureAgeable.func_70636_d(EntityCreatureAgeable.java:95)
	at lycanite.lycanitesmobs.api.entity.EntityCreatureTameable.func_70636_d(EntityCreatureTameable.java:170)
	at lycanite.lycanitesmobs.freshwatermobs.entity.EntityZephyr.func_70636_d(EntityZephyr.java:122)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
	at lycanite.lycanitesmobs.api.entity.EntityCreatureBase.func_70071_h_(EntityCreatureBase.java:1029)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
	Entity Type: freshwatermobs.zephyr (lycanite.lycanitesmobs.freshwatermobs.entity.EntityZephyr)
	Entity ID: 346773
	Entity Name: Keppel Zephyr
	Entity's Exact location: -55.61, 67.11, 61.38
	Entity's Block location: World: (-56,67,61), Chunk: (at 8,4,13 in -4,3; contains blocks -64,0,48 to -49,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.01, -0.00, -0.00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: DeathPlagueGamers
	All players: 2 total; [GCEntityPlayerMP['P3rf3ct_Zer0'/295838, l='DeathPlagueGamers', x=-578.50, y=163.00, z=-54.50], GCEntityPlayerMP['GamerGirl9219'/345677, l='DeathPlagueGamers', x=-54.62, y=67.00, z=61.52]]
	Chunk stats: ServerChunkCache: 596 Drop: 0
	Level seed: 4099119303736329044
	Level generator: ID 06 - Highlands, ver 0. Features enabled: true
	Level generator options: HIGHLANDS
	Level spawn location: World: (-64,64,59), Chunk: (at 0,4,11 in -4,3; contains blocks -64,0,48 to -49,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 235683 game time, 360794 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 117805 (now: false), thunder time: 98607 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 3.10.23-xxxx-std-ipv6-64
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4588345736 bytes (4375 MB) / 5281480704 bytes (5036 MB) up to 5281480704 bytes (5036 MB)
	JVM Flags: 11 total; -Xmx5120M -Xms5120M -Xss2M -XX:PermSize=50m -XX:MaxPermSize=192m -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalMode -XX:+CMSIncrementalPacing -XX:+CMSParallelRemarkEnabled -XX:MaxGCPauseMillis=50
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95

**Comment by Funwayguy** [comment]
The issue is that your inventory is using a single 'byte' to define the slot IDs in this set of loops:
https://github.com/NightKosh/GraveStone-mod/blob/master/src/main/java/gravestone/tileentity/GSGraveStoneItems.java#L191

This causes the byte to top out at slot 127 then roll around to -127 causing an IndexOutOfBoundsException. To fix this you simply need to use integers instead of bytes.

**Comment by DPxKnightxZero** [comment]
Okay something is still not playing nice with gravestones

---- Minecraft Crash Report ----
// Don't do that.

Time: 10/04/15 03:56
Description: Ticking entity

java.lang.IndexOutOfBoundsException: Index: -128, Size: 283
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
	at java.util.LinkedList.get(LinkedList.java:476)
	at gravestone.tileentity.GSGraveStoneItems.setItems(GSGraveStoneItems.java:100)
	at gravestone.tileentity.TileEntityGSGrave.setItems(TileEntityGSGrave.java:64)
	at gravestone.block.BlockGSGraveStone.createOnDeath(BlockGSGraveStone.java:771)
	at gravestone.block.GraveStoneHelper.createGrave(GraveStoneHelper.java:542)
	at gravestone.block.GraveStoneHelper.createPlayerGrave(GraveStoneHelper.java:534)
	at gravestone.core.event.GSEventsHandler.onEntityLivingDeath(GSEventsHandler.java:48)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_490_GSEventsHandler_onEntityLivingDeath_LivingDeathEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:303)
	at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:405)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:855)
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1034)
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:491)
	at micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP.func_70097_a(GCEntityPlayerMP.java:73)
	at net.minecraft.entity.projectile.EntityArrow.func_70071_h_(SourceFile:270)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
	at java.util.LinkedList.get(LinkedList.java:476)
	at gravestone.tileentity.GSGraveStoneItems.setItems(GSGraveStoneItems.java:100)
	at gravestone.tileentity.TileEntityGSGrave.setItems(TileEntityGSGrave.java:64)
	at gravestone.block.BlockGSGraveStone.createOnDeath(BlockGSGraveStone.java:771)
	at gravestone.block.GraveStoneHelper.createGrave(GraveStoneHelper.java:542)
	at gravestone.block.GraveStoneHelper.createPlayerGrave(GraveStoneHelper.java:534)
	at gravestone.core.event.GSEventsHandler.onEntityLivingDeath(GSEventsHandler.java:48)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_490_GSEventsHandler_onEntityLivingDeath_LivingDeathEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:303)
	at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:405)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:855)
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1034)
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:491)
	at micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP.func_70097_a(GCEntityPlayerMP.java:73)
	at net.minecraft.entity.projectile.EntityArrow.func_70071_h_(SourceFile:270)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
	Entity Type: Arrow (net.minecraft.entity.projectile.EntityArrow)
	Entity ID: 14387
	Entity Name: arrow
	Entity's Exact location: -37.85, 64.17, 1.59
	Entity's Block location: World: (-38,64,1), Chunk: (at 10,4,1 in -3,0; contains blocks -48,0,0 to -33,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.31, -0.78, -1.30
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: DeathPlagueGamers
	All players: 2 total; [GCEntityPlayerMP['P3rf3ct_Zer0'/2313, l='DeathPlagueGamers', x=-26.70, y=63.00, z=-15.51], GCEntityPlayerMP['GamerGirl9219'/12476, l='DeathPlagueGamers', x=-37.72, y=64.25, z=0.80]]
	Chunk stats: ServerChunkCache: 256 Drop: 0
	Level seed: 1847526719470730626
	Level generator: ID 06 - Highlands, ver 0. Features enabled: true
	Level generator options: HIGHLANDS
	Level spawn location: World: (-32,64,0), Chunk: (at 0,4,0 in -2,0; contains blocks -32,0,0 to -17,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 216656 game time, 264771 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 130580 (now: false), thunder time: 13768 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 3.10.23-xxxx-std-ipv6-64
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4408553560 bytes (4204 MB) / 5281480704 bytes (5036 MB) up to 5281480704 bytes (5036 MB)
	JVM Flags: 11 total; -Xmx5120M -Xms5120M -Xss2M -XX:PermSize=50m -XX:MaxPermSize=192m -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalMode -XX:+CMSIncrementalPacing -XX:+CMSParallelRemarkEnabled -XX:MaxGCPauseMillis=50
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.104.1360 Minecraft Forge 10.13.3.1360 105 mods loaded, 105 mods active

Another Crash.

**Comment by Funwayguy** [comment]
Same cause as before. Just set InfiniteInvo to a max of 127 or less slots until @NightKosh resolves the issue with the byte limitations on his side.

**Comment by DPxKnightxZero** [comment]
OH!!! Now I get it XD
