### ISSUE TITLE
Twilight Forest compatibility

### ISSUE THREAD

**Issue by NightKosh** [NightKosh/GraveStone-mod#20]
"Charms of Keeping" effect blocked by gravestone

http://www.minecraftforum.net/topic/561673-172-the-twilight-forest-v203-updated-to-minecraft-17/

**Comment by da3dsoul** [comment]
I'll fix this. Well, I made a gravestone mod before, so really I already did and need to submit a pull request.

**Comment by da3dsoul** [comment]
Almost done. I'll have to wait for 1.8. I don't a dev workspace for it and Twilight Forest isn't updated either.

**Comment by NightKosh** [comment]
Thank you very much for help!
But I have small request for future commits: it will be much better to make few smaller commits for their own tasks instead of one big commit. It will be much better for usage, especially to merge them with 1.8 branch.

**Comment by da3dsoul** [comment]
Ah ok. No worries.

**Comment by NightKosh** [comment]
java.lang.NullPointerException
	at gravestone.core.compatibility.GSCompatibilityTwilightForest.handleCharmsOfKeeping(GSCompatibilityTwilightForest.java:33) ~[GSCompatibilityTwilightForest.class:?]
	at gravestone.block.GraveStoneHelper.createPlayerGrave(GraveStoneHelper.java:540) ~[GraveStoneHelper.class:?]
	at gravestone.core.event.GSEventsHandler.onEntityLivingDeath(GSEventsHandler.java:48) ~[GSEventsHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_129_GSEventsHandler_onEntityLivingDeath_LivingDeathEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:298) ~[ForgeHooks.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.onDeath(EntityPlayerMP.java:443) ~[EntityPlayerMP.class:?]
	at net.minecraft.entity.EntityLivingBase.attackEntityFrom(EntityLivingBase.java:938) ~[EntityLivingBase.class:?]
	at net.minecraft.entity.player.EntityPlayer.attackEntityFrom(EntityPlayer.java:1161) ~[EntityPlayer.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.attackEntityFrom(EntityPlayerMP.java:532) ~[EntityPlayerMP.class:?]
	at micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP.attackEntityFrom(GCEntityPlayerMP.java:74) ~[GCEntityPlayerMP.class:?]
	at net.minecraft.command.CommandKill.processCommand(CommandKill.java:32) ~[CommandKill.class:?]
	at net.minecraft.command.CommandHandler.executeCommand(CommandHandler.java:96) [CommandHandler.class:?]
	at net.minecraft.network.NetHandlerPlayServer.handleSlashCommand(NetHandlerPlayServer.java:788) [NetHandlerPlayServer.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processChatMessage(NetHandlerPlayServer.java:764) [NetHandlerPlayServer.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.processPacket(C01PacketChatMessage.java:47) [C01PacketChatMessage.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.processPacket(C01PacketChatMessage.java:68) [C01PacketChatMessage.class:?]
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:241) [NetworkManager.class:?]
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:182) [NetworkSystem.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:726) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:614) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752) [MinecraftServer$2.class:?]

**Comment by NightKosh** [comment]
It looks like Baubles items haven't got a "Slot" tag.
Also backpack from backpack mod was lost.((

**Comment by da3dsoul** [comment]
I see, my bad. I usually don't use baubles and the backpack was probably just a result of crashing, not the code itself. I'll fix.
